name: Update GitHub Profile README

on:
  schedule:
    # Every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual trigger anytime

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Update README
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate Dynamic Content
        run: |
          echo "Updating README content..." 
          # Optional - You can add scripts here if you want to fetch new quotes, etc.

      - name: Commit & Push Changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m '🤖 Automatic Update: README refreshed'
          git push
